### ISSUE TITLE
After the filter is cleared, the highlight still exists, affecting the use!

### ISSUE THREAD

**Issue by x64bugreport** [patois/xray#3]
After the filter is cleared, the highlight still exists, affecting the use!
ida7.7 win11 python3.9
search 00 and clean filter,00 still highlight.
![20220526164127](https://user-images.githubusercontent.com/34920463/170452532-e37b905c-865c-45fb-99ad-e43efe538057.png)

**Comment by patois** [comment]
Thank you very much for your bug report and apologies for the late response. This misbehavior was introduced with SDK changes in IDA 7.7 and should have been fixed using the latest commit ([10fda7eaa330e6c3450643c5b3829cdf759c8b20](https://github.com/patois/xray/commit/10fda7eaa330e6c3450643c5b3829cdf759c8b20)). Please let me know whether this fixes the issue for you so it can be closed.
